// Prerenders the LuaVM docs into crawler-readable formats.
//
// WHY: luavm/index.html is a single-page app – every doc section lives in a
// JavaScript `PAGES` object and is injected into <main> at runtime. Crawlers
// that don't execute JS (OpenAI's GPTBot / OAI-SearchBot, Perplexity, most of
// Bing) therefore see an empty page. The doc-building helpers (toTable /
// renderLuaLines / toCodeblock) are pure string functions with no DOM deps, so
// this script executes the page's own code in Node and produces:
//
//   1. Static HTML baked into <main> (between marker comments) so crawlers read
//      the full docs. The SPA still overwrites <main> for humans on load.
//   2. /llms.txt      – a plain-text index of the docs for AI assistants.
//   3. /llms-full.txt – every section as one plain-text/markdown file.
//
// USAGE: after editing the docs, run  `node luavm/prerender.mjs`  and commit.
// Re-running is idempotent.

import fs from 'node:fs';
import vm from 'node:vm';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FILE = path.join(__dirname, 'index.html');
const ROOT = path.join(__dirname, '..');
const SITE = 'https://www.projectsheldon.me';

const START = '<!-- LUAVM-PRERENDER:START – auto-generated by luavm/prerender.mjs; do not hand-edit -->';
const END = '<!-- LUAVM-PRERENDER:END -->';

const html = fs.readFileSync(FILE, 'utf8');

// 1. Extract the main inline <script> (the one that defines PAGES).
const sStart = html.indexOf('const ICONS = {');
if (sStart === -1) throw new Error('Could not locate the inline script (const ICONS).');
const sEnd = html.indexOf('</script>', sStart);
let script = html.slice(sStart, sEnd);

// Deterministic ids (toCodeblock uses Math.random) → stable diffs on regen.
script = 'let __seed=1;Math.random=function(){__seed=(__seed*9301+49297)%233280;return __seed/233280;};\n' + script;
// Capture PAGES the moment it exists, and htmlToMarkdown once it's defined.
script = script.replace('function currentPath()', '__capture("PAGES", PAGES);\nfunction currentPath()');
script = script.replace('window.addEventListener("hashchange", render)',
  '__capture("MD", typeof htmlToMarkdown==="function"?htmlToMarkdown:null);\nwindow.addEventListener("hashchange", render)');

// 2. Run it under minimal stubs. A universal proxy stands in for every DOM node;
//    location & localStorage are real-ish so string ops don't throw.
const stub = new Proxy(function () {}, {
  get: (_t, p) =>
    p === 'style' ? {} :
    p === 'classList' ? { add() {}, remove() {}, toggle() {}, contains: () => false } :
    p === 'innerHTML' || p === 'textContent' || p === 'value' || p === 'title' ? '' :
    stub,
  set: () => true,
  apply: () => stub,
});

const captured = {};
const ctx = {
  console,
  location: { hash: '', pathname: '/luavm/', href: `${SITE}/luavm/`, search: '' },
  localStorage: { getItem: () => null, setItem() {}, removeItem() {} },
  navigator: { clipboard: { writeText: () => Promise.resolve() }, userAgent: 'node' },
  document: stub,
  setTimeout: () => 0, clearTimeout() {}, setInterval: () => 0, clearInterval() {},
  requestAnimationFrame: () => 0,
  getComputedStyle: () => ({ getPropertyValue: () => '' }),
  matchMedia: () => ({ matches: false, addEventListener() {}, removeEventListener() {} }),
  fetch: () => Promise.reject(new Error('no fetch in prerender')),
  __capture: (k, v) => { captured[k] = v; },
};
ctx.window = ctx;
ctx.addEventListener = () => {};
ctx.scrollTo = () => {};
ctx.globalThis = ctx;
vm.createContext(ctx);
try {
  vm.runInContext(script, ctx, { filename: 'luavm-inline.js' });
} catch (e) {
  if (!captured.PAGES) throw e; // the DOM tail may throw after capture – fine
}
const PAGES = captured.PAGES;
const MD = captured.MD;
if (!PAGES || typeof PAGES !== 'object') throw new Error('PAGES was not captured.');

const slugFor = (p) => (p === '/' ? 'home' : p.replace(/^\//, '').replace(/[^a-z0-9]+/gi, '-'));

// 3. Bake static HTML into <main> so crawlers read every section.
const sections = Object.keys(PAGES).map((p) => {
  const pg = PAGES[p];
  const intro = pg.intro ? `\n      <p class="intro">${pg.intro}</p>` : '';
  const body = (pg.body || '').trim();
  return `    <section id="doc-${slugFor(p)}" class="doc-section" data-path="${p}">\n` +
         `      <h1>${pg.title}</h1>${intro}\n` +
         `      <div class="body">${body}</div>\n` +
         `    </section>`;
}).join('\n');
const block = `${START}\n  <div id="static-docs" class="static-docs" aria-label="LuaVM documentation">\n${sections}\n  </div>\n  ${END}`;

let out;
const iStart = html.indexOf(START);
const iEnd = html.indexOf(END);
if (iStart !== -1 && iEnd !== -1) {
  out = html.slice(0, iStart) + block + html.slice(iEnd + END.length);
} else {
  const target = '<main id="main"></main>';
  if (!html.includes(target)) throw new Error(`Could not find \`${target}\` to inject into.`);
  out = html.replace(target, `<main id="main">\n  ${block}\n  </main>`);
}
fs.writeFileSync(FILE, out);

// 4. HTML → Markdown. Self-contained (the page's htmlToMarkdown mangles the
//    `toTable`/`toCodeblock` output). Code blocks are pulled out to placeholders
//    first – rebuilt from each block's `data-raw` (the original source) – so tag
//    stripping can't corrupt code containing `<` / `>`.
void MD; // (page's converter is captured but intentionally unused)

const decodeEntities = (s) => String(s)
  .replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"')
  .replace(/&#0?39;/g, "'").replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&');

const inline = (s) => decodeEntities(String(s)
  .replace(/<a\b[^>]*href="([^"]*)"[^>]*>([\s\S]*?)<\/a>/g, '[$2]($1)')
  .replace(/<(?:b|strong)\b[^>]*>([\s\S]*?)<\/(?:b|strong)>/g, '**$1**')
  .replace(/<code\b[^>]*>([\s\S]*?)<\/code>/g, '`$1`')
  .replace(/<br\s*\/?>/g, ' ')
  .replace(/<[^>]+>/g, '')
  .replace(/[ \t]+/g, ' ').trim());

function extractCodeblocks(input, store) {
  const marker = '<div class="codeblock-wrap">';
  let res = '', i = 0;
  for (;;) {
    const start = input.indexOf(marker, i);
    if (start === -1) { res += input.slice(i); break; }
    res += input.slice(i, start);
    const re = /<\/?div\b[^>]*>/g; re.lastIndex = start;
    let depth = 0, end = -1, m;
    while ((m = re.exec(input))) {
      depth += m[0][1] === '/' ? -1 : 1;
      if (depth === 0) { end = re.lastIndex; break; }
    }
    if (end === -1) { res += input.slice(start); break; }
    const raw = (input.slice(start, end).match(/data-raw="([^"]*)"/) || [, ''])[1];
    let code = raw;
    try { code = decodeURIComponent(raw); } catch { /* keep raw */ }
    res += `\x00${store.length}\x00`;
    store.push('\n\n```lua\n' + code.replace(/\r/g, '').replace(/​/g, '').trim() + '\n```\n\n');
    i = end;
  }
  return res;
}

function convertTables(h) {
  return h.replace(/<table\b[\s\S]*?<\/table>/g, (tbl) => {
    const headers = [...tbl.matchAll(/<th\b[^>]*>([\s\S]*?)<\/th>/g)].map((m) => inline(m[1]));
    const bodyM = tbl.match(/<tbody\b[^>]*>([\s\S]*?)<\/tbody>/);
    const rows = [...(bodyM ? bodyM[1] : tbl).matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/g)]
      .map((r) => [...r[1].matchAll(/<td\b[^>]*>([\s\S]*?)<\/td>/g)].map((c) => inline(c[1]).replace(/\|/g, '\\|')));
    if (!headers.length && !rows.length) return '';
    const cols = headers.length || (rows[0] ? rows[0].length : 1);
    const head = headers.length ? headers : Array(cols).fill(' ');
    return '\n\n| ' + head.join(' | ') + ' |\n| ' + head.map(() => '---').join(' | ') + ' |\n' +
      rows.map((r) => '| ' + r.join(' | ') + ' |').join('\n') + '\n\n';
  });
}

function toMd(h) {
  const store = [];
  let s = extractCodeblocks(String(h || ''), store);
  s = convertTables(s);
  s = s
    .replace(/<h[12]\b[^>]*>([\s\S]*?)<\/h[12]>/g, (_, t) => `\n\n## ${inline(t)}\n\n`)
    .replace(/<h3\b[^>]*>([\s\S]*?)<\/h3>/g, (_, t) => `\n\n### ${inline(t)}\n\n`)
    .replace(/<h[456]\b[^>]*>([\s\S]*?)<\/h[456]>/g, (_, t) => `\n\n#### ${inline(t)}\n\n`)
    .replace(/<li\b[^>]*>([\s\S]*?)<\/li>/g, (_, t) => `- ${inline(t)}\n`)
    .replace(/<\/?(?:ul|ol)\b[^>]*>/g, '\n')
    .replace(/<p\b[^>]*>([\s\S]*?)<\/p>/g, (_, t) => `\n\n${inline(t)}\n\n`);
  s = s.replace(/<[^>]+>/g, '');          // drop any remaining tags (safe: code is stashed)
  s = decodeEntities(s);
  s = s.replace(/^[ \t]+/gm, '');         // strip leading indent (code is still stashed)
  s = s.replace(/[ \t]+\n/g, '\n').replace(/\n{3,}/g, '\n\n').trim();
  s = s.replace(/\x00(\d+)\x00/g, (_, n) => store[+n]);  // restore code blocks
  return s.replace(/[ \t]+\n/g, '\n').replace(/\n{3,}/g, '\n\n').trim();
}

// 5. Emit llms-full.txt (every section) and llms.txt (index).
const fullParts = [
  '# Sheldon LuaVM – Full Documentation',
  '',
  "> Scripting reference and API documentation for Sheldon's LuaVM, a customizable Lua scripting environment for Roblox.",
  `> Source: ${SITE}/luavm/`,
  '> This plain-text file mirrors the full documentation for AI assistants and search tools.',
  '',
];
for (const p of Object.keys(PAGES)) {
  const pg = PAGES[p];
  fullParts.push('', '---', '', `## ${pg.title}`, '');
  if (pg.intro) fullParts.push(toMd(pg.intro), '');
  const bodyMd = toMd(pg.body);
  if (bodyMd) fullParts.push(bodyMd, '');
}
const fullText = fullParts.join('\n').replace(/\n{3,}/g, '\n\n').trim() + '\n';
fs.writeFileSync(path.join(ROOT, 'llms-full.txt'), fullText);

const toc = Object.keys(PAGES)
  .map((p) => `- [${PAGES[p].title}](${SITE}/luavm/#${p})`)
  .join('\n');
const indexText = `# Project Sheldon – LuaVM

> Sheldon LuaVM is a customizable Lua scripting environment for Roblox. This file indexes the documentation for AI assistants and LLMs.

## Documentation

- [LuaVM Documentation](${SITE}/luavm/): Full scripting reference – globals, GUI, ImGui, drawing, input, files, internet, memory, cheat, tween, entities, instances, signals and more.
- [LuaVM Documentation (full plain text)](${SITE}/llms-full.txt): Every documentation section concatenated as one markdown file – the most reliable source for AI systems.
- [API Docs](${SITE}/api-docs/): Project Sheldon API reference.

## Sections

${toc}
`;
fs.writeFileSync(path.join(ROOT, 'llms.txt'), indexText);

console.log(`✓ ${Object.keys(PAGES).length} sections`);
console.log(`  • luavm/index.html   static block ${(block.length / 1024).toFixed(1)} KB`);
console.log(`  • llms-full.txt      ${(fullText.length / 1024).toFixed(1)} KB`);
console.log(`  • llms.txt           ${(indexText.length / 1024).toFixed(1)} KB`);
